sonar.projectKey=CircuitBreakDevs_Proyecto_Calidad_Software
sonar.organization=circuitbreakdevs

# Rutas reales del proyecto
sonar.sources=src
sonar.tests=pruebas

# Python y cobertura
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

# Excluir plantillas HTML de reglas Python
sonar.exclusions=src/interfaz/templates/**

sonar.sourceEncoding=UTF-8
